### ISSUE TITLE
Create index.html w home section + ids

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/bandz-the-frog-sayeth-croak#1]
each section has a class of container
each container has an individual id noting the section
(news, albums, tour dates, band members, photos/video)
make html bplate

**Comment by ledugani** [comment]
# Story
# Acceptance Criteria
# Tech Notes

**Comment by ghost** [comment]
# Story
- user visits website to see cool new fave band

# Acceptance Criteria
**when** the developer loads the page 
**then** when they look at the code they should see the technical details below have been created


# Technical Details
- add links to main.js and main.css
- write printToDom function 
- function is global across all pages w/ JS: printToDom(stringToPrint , id) { id.innerHTML = stringToPrint; }
- each page has a div with a class of container
- each container has an individual id noting the page
- (news, albums, tour dates, band members, photos/video)
- make html bplate
- expect that the nav maker will be contributing the navbar to put here
- band name in middle of the page -- largest element on page

**Comment by ghost** [comment]
Example:
`<div class="container" id="news">`
