### ISSUE TITLE
Create Data: Photos Page

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/bandz-the-frog-sayeth-croak#17]

**Comment by ghost** [comment]
# Story
- When the user visits the photos page there should be data on the page

# Acceptance Criteria
**When** the DOM is being built
**Then** There should be an array of data to loop through
**And** Display to the page

# Technical Details
- Create an array of objects called photosArray
- each object will have a set of key: value pairs

**Comment by AlexOrga** [comment]
👍
