### ISSUE TITLE
Create Page: Photos

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/bandz-the-frog-sayeth-croak#5]
# Story
User visits the photos page on the site to see photos of the band

# Acceptance Criteria
**When** A user visits the photos page of the website
**Then** sees different photos of the band arranged in a grid

# Technical Notes
- Create a photos.html file
- Write an html boilerplate
- Create a div with an id "photos-container"
- Link to main.css
- Link to main.js

**Comment by ghost** [comment]
![screen shot 2018-03-14 at 10 23 23 pm](https://user-images.githubusercontent.com/33577725/37442895-be86d9da-27d6-11e8-9a3a-c55053fde1c0.png)

**Comment by annamd115** [comment]
👍
