### ISSUE TITLE
Create Page: Band 

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/bandz-the-frog-sayeth-croak#6]
# Story
User visits the band page on the site to learn about and see images of the band

# Acceptance Criteria
**When** A user visits the band page of the website
**Then** sees different members of the band and a bio in a grid

# Technical Notes
- Create a band.html file
- Write an html boilerplate
- Create a div with an id "band-container"
- Link to main.css
- Link to main.js

**Comment by AlexOrga** [comment]
closes #28
